-- Customer spend, a materialized table over transactions, per environment; ${env} is the prefix, test or prod.
-- The query only: the table's name, key, buckets, changelog mode, and format are the resource's arguments in
-- flink.tf, and Flink registers the table's schema from these four columns.
--
-- SELECT
--   customer_id,
--   COUNT(*)        AS purchases,
--   SUM(price)      AS spent,
--   MAX(created_at) AS last_purchase
-- FROM `${env}.transactions`
-- GROUP BY customer_id
--
-- Notes: one row per customer, updated by every transaction; upsert mode keeps the latest row per key on the
-- compacted topic, which is the materialized view. No trailing semicolon, the resource submits the query as is.
