-- Settles orders against offers into transactions, per environment; ${env} is the prefix, test or prod.
-- A stream-to-stream join: both sides are event streams, so the join is bounded in time. An order settles against
-- the offer for the same product in the same region that was open when the order was placed.
--
-- INSERT INTO `${env}.transactions`
-- SELECT
--   UUID()                                                                   AS transaction_id,
--   ROW(o.id, o.customer_id, o.product_id, o.created_at)                     AS order_ref,    -- as order.proto
--   ROW(f.offer_id, f.product_id, f.price, f.seller_id, f.created_at)        AS offer_ref,    -- as offer.proto
--   o.customer_id, f.seller_id, f.price,
--   o.created_at                                                             AS created_at
-- FROM `${env}.orders` o
-- JOIN `${env}.offers` f
--   ON o.region = f.region                          -- the region travels in the ce_region header: expose it as a
--  AND o.product_id = f.product_id                  -- column, or join on product alone until the header is a column
--  AND o.created_at BETWEEN f.created_at AND f.created_at + INTERVAL '10' MINUTE;
--
-- Notes: the column list and the nested rows match transaction.proto field by field, the registry holds it already.
-- created_at is a TIMESTAMP column; the interval join needs a time attribute, so either use `$rowtime` on both
-- sides, the record timestamp Flink infers, or ALTER TABLE ... MODIFY WATERMARK on created_at once, in the console.
